In [1]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 50.5 MB/s eta 0:00:00


In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

In [4]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')



[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
vec_king = wv['king']

In [6]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [7]:
vec_king.shape

(300,)

In [8]:
wv.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [9]:
wv.most_similar("happy")

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [13]:
wv.similarity("hockey","sports")

np.float32(0.53541523)

In [11]:
vec = wv['king']-wv['man']+wv['woman']

In [12]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [14]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [17]:
# Text Classification with Word2Vec and AverageWord2Vec

from google.colab import files

uploaded = files.upload()

Saving spam.csv to spam.csv


In [19]:
import pandas as pd

messages = pd.read_csv('spam.csv',encoding='latin-1')

messages = messages[['v1','v2']]
messages.columns = ['label','text']
messages.head()

,label,text
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [53]:
import nltk
import re
import gensim
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk import sent_tokenize
from tqdm import tqdm
import numpy as np
from gensim.utils import simple_preprocess
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [22]:
lm = WordNetLemmatizer()

In [80]:
corpus = []

for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['text'][i])
  review = review.lower()
  review = review.split()
  review = [lm.lemmatize(word) for word in review if word not in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [81]:
words = []

for sent in corpus:
  sent_token = sent_tokenize(sent)
  for word in sent_token:
    words.append(simple_preprocess(word))

In [82]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [83]:
model = gensim.models.Word2Vec(words)

In [84]:
## To get all the vocabulary
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'text',
 'love',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'going',
 'home',
 'stop',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'pls',
 'please',
 'co',
 'msg',
 'min',
 'dear',
 'make',
 'night',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'claim',
 'great',
 'hope',
 'oh',
 'hey',
 'number',
 'happy',
 'friend',
 'wat',
 'give',
 'work',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'said',
 'cash',
 'win',
 'yeah',
 'amp',
 'really',
 'life',
 'im',
 'babe',
 'meet',
 'find',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'miss',
 'would',
 'com',
 'also',
 'nokia',
 'anything',
 'lol',
 'care',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',


In [85]:
model.corpus_count

5564

In [86]:
model.epochs

5

In [87]:
model.wv.similar_by_word("good")

[('day', 0.9995838403701782),
 ('want', 0.9995777606964111),
 ('much', 0.9995678663253784),
 ('go', 0.9995654821395874),
 ('give', 0.9995539784431458),
 ('get', 0.9995523691177368),
 ('need', 0.99955153465271),
 ('still', 0.9995514154434204),
 ('like', 0.9995479583740234),
 ('miss', 0.9995474815368652)]

In [88]:
model.wv['good']

array([-0.24160619,  0.45909694,  0.00305163,  0.07093074,  0.06219819,
       -0.67904305,  0.1047089 ,  0.8046298 , -0.181915  , -0.2000251 ,
       -0.20245825, -0.6026537 , -0.08788771,  0.10761309,  0.02154963,
       -0.3493605 ,  0.02302944, -0.49951962, -0.03038912, -0.8163657 ,
        0.1087267 ,  0.18349199, -0.02427731, -0.11803588, -0.16247332,
        0.00812719, -0.42537245, -0.35073492, -0.38027275,  0.00597691,
        0.46726546,  0.10122146,  0.1614247 , -0.04657124, -0.20395494,
        0.45209992, -0.06567562, -0.42535555, -0.29533568, -0.8732502 ,
       -0.04934235, -0.3431559 ,  0.01991904,  0.17365327,  0.48690554,
       -0.08100138, -0.2581496 , -0.0097278 ,  0.31601894,  0.25955182,
        0.14109918, -0.27446303, -0.04632451,  0.05314369, -0.4574485 ,
        0.21733771,  0.3182108 ,  0.10049133, -0.5910205 ,  0.04480923,
        0.05168328,  0.20719159, -0.29972595, -0.03999308, -0.54334545,
        0.31473872,  0.16609003,  0.26286012, -0.53826964,  0.53

In [102]:
def avg_word2vec(doc):
  # axis=0 ensures we average the vectors, not the individual scalars
  # We also handle the case where a document might be empty to avoid errors
  vecs = [model.wv[word] for word in doc if word in model.wv.index_to_key]
  if not vecs:
    return np.zeros(model.vector_size)
  return np.mean(vecs, axis=0)

In [103]:
X = []

for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

100%|██████████| 5564/5564 [00:00<00:00, 12085.87it/s]


In [104]:
len(X)

5564

In [148]:
## Dependent features
y = messages[list(map(lambda x: len(x)>0, corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:,0].values

In [142]:
y.shape

(5564,)

In [143]:
y.shape

(5564,)

In [139]:
df = pd.DataFrame()

for i in range(0, len(X)):
    row = pd.DataFrame(X[i].reshape(1, -1))
    df = pd.concat([df, row], ignore_index=True)

In [140]:
df.shape

(5564, 100)

In [147]:
X = df

In [152]:
from sklearn.model_selection import train_test_split

# Ensure X and y are correctly aligned and split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [153]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
1730,-0.174640,0.347136,-0.007701,0.066786,0.054572,-0.501997,0.075998,0.610919,-0.120417,-0.141141,...,0.465077,0.221281,-0.074911,0.049156,0.543065,0.412270,0.136508,-0.302084,0.187969,-0.020638
5123,-0.174752,0.332152,-0.002473,0.060184,0.050112,-0.491179,0.083083,0.597046,-0.128283,-0.137968,...,0.449004,0.216053,-0.075080,0.056312,0.525420,0.411643,0.138930,-0.286681,0.177364,-0.028236
1476,-0.138872,0.280065,0.001079,0.048985,0.036609,-0.418517,0.067913,0.510946,-0.112433,-0.121042,...,0.384421,0.182195,-0.065604,0.051414,0.442956,0.349670,0.120430,-0.247737,0.144556,-0.023857
2867,-0.222595,0.452649,-0.002888,0.082594,0.060109,-0.671463,0.116726,0.822646,-0.174084,-0.191796,...,0.615386,0.300926,-0.113671,0.076975,0.711151,0.553097,0.180927,-0.404385,0.247301,-0.029394
4896,-0.139809,0.273456,-0.005878,0.052171,0.043389,-0.394942,0.058808,0.478254,-0.101772,-0.109432,...,0.356820,0.171019,-0.054452,0.043799,0.419359,0.326067,0.108635,-0.231932,0.143073,-0.015506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,-0.118771,0.232465,0.003647,0.035705,0.035202,-0.352669,0.058519,0.423392,-0.089810,-0.101988,...,0.314760,0.152074,-0.057903,0.043171,0.367309,0.284529,0.098017,-0.202142,0.123141,-0.021066
5191,-0.071070,0.139898,0.008483,0.028201,0.021652,-0.207421,0.036778,0.250604,-0.053276,-0.056709,...,0.190308,0.089379,-0.031098,0.025783,0.222389,0.174514,0.061967,-0.122035,0.076638,-0.009920
5226,-0.163505,0.328241,0.006176,0.059485,0.045931,-0.490097,0.086831,0.603199,-0.129471,-0.142852,...,0.447565,0.219905,-0.084101,0.060797,0.518203,0.402807,0.140083,-0.294689,0.174662,-0.022215
5390,-0.202916,0.393408,0.004505,0.063296,0.056227,-0.600328,0.100446,0.719261,-0.157925,-0.176087,...,0.543969,0.261288,-0.092810,0.075166,0.621792,0.485588,0.166138,-0.343429,0.206942,-0.040334


In [154]:
from sklearn.ensemble import RandomForestClassifier

# Initialize and fit the model
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [155]:
rf_model.score(X_test, y_test)

0.9613656783468104

In [156]:
y_pred = rf_model.predict(X_test)

In [158]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9613656783468104
[[114  28]
 [ 15 956]]
              precision    recall  f1-score   support

       False       0.88      0.80      0.84       142
        True       0.97      0.98      0.98       971

    accuracy                           0.96      1113
   macro avg       0.93      0.89      0.91      1113
weighted avg       0.96      0.96      0.96      1113

